# email_service.py
# Handles transactional email via SendGrid.
#
# Setup:
#   pip install sendgrid
#   Add to .env:
#     SENDGRID_API_KEY=SG.xxxxxxxxxxxx
#     SENDGRID_FROM_EMAIL=noreply@yourdomain.com
#     FRONTEND_URL=https://your-deployed-app.com   (for link generation)

import os
import logging
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

logger = logging.getLogger(__name__)


class EmailService:
    def __init__(self):
        self.api_key       = os.getenv('SENDGRID_API_KEY')
        self.from_email    = os.getenv('SENDGRID_FROM_EMAIL', 'noreply@legobrickapp.com')
        self.frontend_url  = os.getenv('FRONTEND_URL', 'http://localhost:5000')
        self.enabled       = bool(self.api_key)

        if not self.enabled:
            logger.warning(
                "EmailService: SENDGRID_API_KEY not set — emails will be logged "
                "to console only. Set the key in .env to enable real email delivery."
            )

    # ── Public methods ────────────────────────────────────────────────────────

    def send_verification_email(self, to_email: str, username: str, token: str) -> bool:
        """
        Send an account verification email with a one-click confirmation link.

        Args:
            to_email:  Recipient email address.
            username:  Display name shown in the email body.
            token:     Signed verification token (generated by User.generate_verification_token()).

        Returns:
            True if the email was sent (or logged) successfully, False on error.
        """
        verify_url = f"{self.frontend_url}/verify-email?token={token}"

        subject = "Confirm your LEGO Brick App account"
        html_content = f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: #FFD700; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
                <h1 style="color: #1A1A2E; margin: 0;">🧱 LEGO Brick App</h1>
            </div>
            <div style="background: #f9f9f9; padding: 30px; border-radius: 0 0 8px 8px;">
                <h2 style="color: #1A1A2E;">Welcome, {username}!</h2>
                <p style="color: #555; font-size: 16px;">
                    Thanks for registering. Please confirm your email address by clicking the button below.
                </p>
                <div style="text-align: center; margin: 30px 0;">
                    <a href="{verify_url}"
                       style="background: #D01012; color: white; padding: 14px 28px;
                              text-decoration: none; border-radius: 8px; font-size: 16px;
                              font-weight: bold;">
                        Confirm Email Address
                    </a>
                </div>
                <p style="color: #999; font-size: 13px;">
                    This link expires in 24 hours. If you didn't create an account, you can ignore this email.
                </p>
                <p style="color: #999; font-size: 12px;">
                    Or copy this link into your browser:<br>
                    <a href="{verify_url}" style="color: #006DB7;">{verify_url}</a>
                </p>
            </div>
        </div>
        """
        return self._send(to_email, subject, html_content)

    def send_password_reset_email(self, to_email: str, username: str, token: str) -> bool:
        """
        Send a password reset email with a one-click reset link.

        Args:
            to_email:  Recipient email address.
            username:  Display name shown in the email body.
            token:     Signed reset token (generated by User.generate_reset_token()).

        Returns:
            True if sent successfully, False on error.
        """
        reset_url = f"{self.frontend_url}/reset-password?token={token}"

        subject = "Reset your LEGO Brick App password"
        html_content = f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: #FFD700; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
                <h1 style="color: #1A1A2E; margin: 0;">🧱 LEGO Brick App</h1>
            </div>
            <div style="background: #f9f9f9; padding: 30px; border-radius: 0 0 8px 8px;">
                <h2 style="color: #1A1A2E;">Password Reset Request</h2>
                <p style="color: #555; font-size: 16px;">
                    Hi {username}, we received a request to reset your password.
                    Click the button below to choose a new one.
                </p>
                <div style="text-align: center; margin: 30px 0;">
                    <a href="{reset_url}"
                       style="background: #D01012; color: white; padding: 14px 28px;
                              text-decoration: none; border-radius: 8px; font-size: 16px;
                              font-weight: bold;">
                        Reset My Password
                    </a>
                </div>
                <p style="color: #999; font-size: 13px;">
                    This link expires in 1 hour. If you didn't request a password reset,
                    you can safely ignore this email — your password won't change.
                </p>
                <p style="color: #999; font-size: 12px;">
                    Or copy this link into your browser:<br>
                    <a href="{reset_url}" style="color: #006DB7;">{reset_url}</a>
                </p>
            </div>
        </div>
        """
        return self._send(to_email, subject, html_content)

    def send_welcome_email(self, to_email: str, username: str) -> bool:
        """
        Send a welcome email after the user has verified their account.

        Args:
            to_email:  Recipient email address.
            username:  Display name shown in the email body.
        """
        subject = "Your LEGO Brick App account is ready!"
        html_content = f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: #FFD700; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
                <h1 style="color: #1A1A2E; margin: 0;">🧱 LEGO Brick App</h1>
            </div>
            <div style="background: #f9f9f9; padding: 30px; border-radius: 0 0 8px 8px;">
                <h2 style="color: #1A1A2E;">You're all set, {username}! 🎉</h2>
                <p style="color: #555; font-size: 16px;">
                    Your account has been verified. Here's what you can do:
                </p>
                <ul style="color: #555; font-size: 15px; line-height: 2;">
                    <li>📷 <strong>Scan bricks</strong> — take a photo to identify your LEGO pieces</li>
                    <li>📦 <strong>Build inventory</strong> — track every brick you own</li>
                    <li>🔨 <strong>Find sets</strong> — see which LEGO sets you can build right now</li>
                </ul>
                <div style="text-align: center; margin: 30px 0;">
                    <a href="{self.frontend_url}"
                       style="background: #006DB7; color: white; padding: 14px 28px;
                              text-decoration: none; border-radius: 8px; font-size: 16px;
                              font-weight: bold;">
                        Open the App
                    </a>
                </div>
            </div>
        </div>
        """
        return self._send(to_email, subject, html_content)

    # ── Private helpers ───────────────────────────────────────────────────────

    def _send(self, to_email: str, subject: str, html_content: str) -> bool:
        """
        Internal method — sends an HTML email via SendGrid, or logs it to
        console if SENDGRID_API_KEY is not configured.
        """
        if not self.enabled:
            # Development fallback: print the email to the console
            logger.info(
                f"\n{'='*60}\n"
                f"[EMAIL - NOT SENT - no API key]\n"
                f"To:      {to_email}\n"
                f"Subject: {subject}\n"
                f"{'='*60}"
            )
            return True

        message = Mail(
            from_email=self.from_email,
            to_emails=to_email,
            subject=subject,
            html_content=html_content,
        )
        try:
            sg = SendGridAPIClient(self.api_key)
            response = sg.send(message)
            logger.info(f"Email sent to {to_email} — status {response.status_code}")
            return response.status_code in (200, 202)
        except Exception as e:
            logger.error(f"Failed to send email to {to_email}: {e}")
            return False


# Module-level singleton — import and use anywhere in the app:
#   from email_service import email_service
#   email_service.send_verification_email(...)
email_service = EmailService()