# backend/lego_sets_db.py
# Real LEGO set Bill of Materials (BOM) data.
# brick_id matches the brick_id stored in inventory_items table.
# color matches the color names returned by LegoColorClassifier.

LEGO_SETS = [
    {
        "set_id": "10698",
        "name": "Classic Creative Brick Box",
        "theme": "Classic",
        "total_pieces": 790,
        "difficulty": "beginner",
        "estimated_build_time": "2-3 hours",
        "pieces": [
            {"brick_id": "Brick 2x4",  "color": "Bright Red",    "qty": 20},
            {"brick_id": "Brick 2x4",  "color": "Bright Blue",   "qty": 15},
            {"brick_id": "Brick 2x4",  "color": "Bright Yellow", "qty": 15},
            {"brick_id": "Brick 2x2",  "color": "Bright Red",    "qty": 10},
            {"brick_id": "Brick 2x2",  "color": "Bright Blue",   "qty": 10},
            {"brick_id": "Brick 2x2",  "color": "White",         "qty": 10},
            {"brick_id": "Plate 2x4",  "color": "Bright Yellow", "qty": 12},
            {"brick_id": "Plate 2x4",  "color": "Bright Green",  "qty": 12},
            {"brick_id": "Plate 1x2",  "color": "Black",         "qty": 8},
            {"brick_id": "Tile 2x2",   "color": "White",         "qty": 6},
            {"brick_id": "Brick 1x2",  "color": "Bright Red",    "qty": 15},
            {"brick_id": "Brick 1x4",  "color": "Bright Blue",   "qty": 10},
            {"brick_id": "Plate 2x2",  "color": "Bright Yellow", "qty": 8},
        ],
    },
    {
        "set_id": "31134",
        "name": "Space Rocket",
        "theme": "Creator",
        "total_pieces": 285,
        "difficulty": "intermediate",
        "estimated_build_time": "3-4 hours",
        "pieces": [
            {"brick_id": "Brick 2x4",   "color": "White",          "qty": 12},
            {"brick_id": "Brick 2x2",   "color": "White",          "qty": 8},
            {"brick_id": "Brick 1x2",   "color": "Bright Red",     "qty": 6},
            {"brick_id": "Plate 2x4",   "color": "White",          "qty": 8},
            {"brick_id": "Plate 1x2",   "color": "Dark Stone Grey","qty": 6},
            {"brick_id": "Tile 1x2",    "color": "White",          "qty": 4},
            {"brick_id": "Slope 45 2x2","color": "White",          "qty": 6},
            {"brick_id": "Brick 1x4",   "color": "Dark Stone Grey","qty": 4},
        ],
    },
    {
        "set_id": "60388",
        "name": "Gaming Tournament Truck",
        "theme": "City",
        "total_pieces": 344,
        "difficulty": "intermediate",
        "estimated_build_time": "3-4 hours",
        "pieces": [
            {"brick_id": "Brick 2x4",   "color": "Black",          "qty": 8},
            {"brick_id": "Brick 2x2",   "color": "Bright Blue",    "qty": 6},
            {"brick_id": "Plate 2x4",   "color": "Black",          "qty": 6},
            {"brick_id": "Plate 1x4",   "color": "Bright Blue",    "qty": 4},
            {"brick_id": "Tile 2x2",    "color": "Dark Stone Grey","qty": 4},
            {"brick_id": "Brick 1x2",   "color": "Black",          "qty": 8},
            {"brick_id": "Slope 45 2x2","color": "Black",          "qty": 4},
        ],
    },
    {
        "set_id": "11013",
        "name": "Creative Transparent Bricks",
        "theme": "Classic",
        "total_pieces": 500,
        "difficulty": "beginner",
        "estimated_build_time": "1-2 hours",
        "pieces": [
            {"brick_id": "Brick 2x4",  "color": "Bright Red",    "qty": 15},
            {"brick_id": "Brick 2x2",  "color": "Bright Yellow", "qty": 12},
            {"brick_id": "Plate 2x4",  "color": "Bright Green",  "qty": 10},
            {"brick_id": "Plate 1x2",  "color": "Bright Blue",   "qty": 10},
            {"brick_id": "Brick 1x2",  "color": "White",         "qty": 8},
            {"brick_id": "Tile 1x1",   "color": "Bright Yellow", "qty": 8},
        ],
    },
    {
        "set_id": "42151",
        "name": "Bugatti Bolide",
        "theme": "Technic",
        "total_pieces": 905,
        "difficulty": "advanced",
        "estimated_build_time": "5-6 hours",
        "pieces": [
            {"brick_id": "Brick 2x4",   "color": "Dark Stone Grey","qty": 20},
            {"brick_id": "Brick 1x2",   "color": "Black",          "qty": 16},
            {"brick_id": "Plate 2x4",   "color": "Dark Stone Grey","qty": 12},
            {"brick_id": "Tile 2x2",    "color": "Dark Stone Grey","qty": 10},
            {"brick_id": "Brick 2x2",   "color": "Black",          "qty": 14},
            {"brick_id": "Slope 45 2x2","color": "Dark Stone Grey","qty": 8},
            {"brick_id": "Brick 1x4",   "color": "Black",          "qty": 10},
            {"brick_id": "Plate 1x4",   "color": "Dark Stone Grey","qty": 8},
        ],
    },
]
